var searchData=
[
  ['icombataction_356',['ICombatAction',['../interface_combat_1_1_actions_1_1_i_combat_action.html',1,'Combat::Actions']]],
  ['icombathandler_357',['ICombatHandler',['../interface_combat_1_1_handlers_1_1_i_combat_handler.html',1,'Combat::Handlers']]],
  ['icombatmovemaker_358',['ICombatMoveMaker',['../interface_combat_1_1_moves_1_1_i_combat_move_maker.html',1,'Combat::Moves']]],
  ['idamagedealer_359',['IDamageDealer',['../interface_combat_1_1_damage_1_1_i_damage_dealer.html',1,'Combat::Damage']]],
  ['idamagetaker_360',['IDamageTaker',['../interface_combat_1_1_damage_1_1_i_damage_taker.html',1,'Combat::Damage']]],
  ['idragprovider_361',['IDragProvider',['../interface_controls_1_1_i_drag_provider.html',1,'Controls']]],
  ['ihealth_362',['IHealth',['../interface_combat_1_1_i_health.html',1,'Combat']]],
  ['ilevelpreset_363',['ILevelPreset',['../interface_levels_1_1_i_level_preset.html',1,'Levels']]],
  ['ilevelpreseteditorextension_364',['ILevelPresetEditorExtension',['../interface_levels_1_1_custom_editors_1_1_extensions_1_1_i_level_preset_editor_extension.html',1,'Levels::CustomEditors::Extensions']]],
  ['iminimapdrawcondition_365',['IMinimapDrawCondition',['../interface_u_i_1_1_minimaps_1_1_extensions_1_1_i_minimap_draw_condition.html',1,'UI::Minimaps::Extensions']]],
  ['iminimapdrawhandler_366',['IMinimapDrawHandler',['../interface_u_i_1_1_minimaps_1_1_extensions_1_1_i_minimap_draw_handler.html',1,'UI::Minimaps::Extensions']]],
  ['iminimapextension_367',['IMinimapExtension',['../interface_u_i_1_1_minimaps_1_1_extensions_1_1_i_minimap_extension.html',1,'UI::Minimaps::Extensions']]],
  ['imodifiablehealth_368',['IModifiableHealth',['../interface_combat_1_1_i_modifiable_health.html',1,'Combat']]],
  ['imovementinputprovider_369',['IMovementInputProvider',['../interface_controls_1_1_i_movement_input_provider.html',1,'Controls']]],
  ['irotatedtransform_370',['IRotatedTransform',['../interface_controls_1_1_i_rotated_transform.html',1,'Controls']]],
  ['iruntimelevelbuilder_371',['IRuntimeLevelBuilder',['../interface_levels_1_1_runtime_1_1_i_runtime_level_builder.html',1,'Levels::Runtime']]]
];
